#!/bin/bash

# Array of VSCode extensions to install
extensions=(
    "alfredbirk.tailwind-documentation"
    "angular.ng-template"
    "anthropic.claude-code"
    "bradlc.vscode-tailwindcss"
    "brandonfowler.exe-runner"
    "christian-kohler.npm-intellisense"
    "davidanson.vscode-markdownlint"
    "dbaeumer.vscode-eslint"
    "docker.docker"
    "donjayamanne.githistory"
    "dsznajder.es7-react-js-snippets"
    "eamodio.gitlens"
    "ecmel.vscode-html-css"
    "esbenp.prettier-vscode"
    "firefox-devtools.vscode-firefox-debug"
    "formulahendry.code-runner"
    "franneck94.c-cpp-runner"
    "github.copilot"
    "github.copilot-chat"
    "github.remotehub"
    "github.vscode-pull-request-github"
    "gitlab.gitlab-workflow"
    "glenn2223.live-sass"
    "google.geminicodeassist"
    "kilocode.kilo-code"
    "lonefy.vscode-js-css-html-formatter"
    "mechatroner.rainbow-csv"
    "ms-azuretools.vscode-containers"
    "ms-azuretools.vscode-docker"
    "ms-edgedevtools.vscode-edge-devtools"
    "ms-kubernetes-tools.vscode-kubernetes-tools"
    "ms-python.debugpy"
    "ms-python.python"
    "ms-python.vscode-pylance"
    "ms-python.vscode-python-envs"
    "ms-toolsai.jupyter"
    "ms-toolsai.jupyter-keymap"
    "ms-toolsai.jupyter-renderers"
    "ms-toolsai.vscode-jupyter-cell-tags"
    "ms-toolsai.vscode-jupyter-slideshow"
    "ms-vscode-remote.remote-containers"
    "ms-vscode-remote.remote-ssh"
    "ms-vscode-remote.remote-ssh-edit"
    "ms-vscode-remote.remote-wsl"
    "ms-vscode-remote.vscode-remote-extensionpack"
    "ms-vscode.azure-repos"
    "ms-vscode.cpptools"
    "ms-vscode.cpptools-extension-pack"
    "ms-vscode.cpptools-themes"
    "ms-vscode.makefile-tools"
    "ms-vscode.powershell"
    "ms-vscode.remote-explorer"
    "ms-vscode.remote-repositories"
    "ms-vscode.remote-server"
    "ms-vscode.vscode-speech"
    "openai.chatgpt"
    "plex.vscode-protolint"
    "postman.postman-for-vscode"
    "prozense.react-exclusive-auto-importer"
    "pymzor.language-proto-webots"
    "rangav.vscode-thunder-client"
    "redhat.java"
    "redhat.vscode-yaml"
    "ritwickdey.liveserver"
    "rodrigovalles.es7-react-js-snippets"
    "samghelms.jupyter-notebook-vscode"
    "saoudrizwan.claude-dev"
    "vadimcn.vscode-lldb"
    "visualstudioexptteam.intellicode-api-usage-examples"
    "visualstudioexptteam.vscodeintellicode"
)

echo "Starting VSCode extension installation..."

# Install each extension
for extension in "${extensions[@]}"; do
    echo "Installing $extension..."
    code --install-extension "$extension"
    
    # Add a small delay between installations
    sleep 1
done

echo "All extensions have been installed!"
